#!/usr/bin/env python3
"""extract_determinate.py v1.0 — 2026-08-09

Generates the C3 ANSWER-CHECK WORKSHEET for a mathematics chapter's installed library.

Why this exists (testing.md C3, maths sub-check, added at template 2.9): mathematics is the
only subject whose assessment items carry DETERMINATE answers — a value that is either right
or wrong, with no reading of intent. Science and social sciences ship `expected_elements` and
`look_for` instead, which are judged, not computed. At S4's C3 one of 23 determinate answers
across the ch 4 library was WRONG (ARV-D-084) and nothing in the pipeline looked at it: the
certifier checks structure, STEP 6 checks option order, and `verified: true` is the model's own
claim about itself.

What this script does and does NOT do. It EXTRACTS — walks the installed canonicals, finds
every item carrying an `expected_answer` or a `method_one_line`, and writes a runnable sympy
stub per item with the stem and the claimed answer in view. It does NOT verify. Stems are
prose ("Compute 312^2 by writing 312 = 300 + 10 + 2 and applying the identity ..."), and a
parser that guesses at them would fail silently — which is the exact failure this check
exists to prevent. So extraction is mechanical and transcription stays a judgement, made by
the checker, from the STEM.

The one rule that makes the check worth running: **transcribe from the question, never from
`method_one_line`.** The wrong answer at S4 sat beside a method line that had already worked
out the right one; a checker copying the method would have confirmed the file against itself.

Usage (from the repo root):

    python3 genon/extract_determinate.py mathematics ix 4
    # → genon/out/answer_checks/mathematics_ix_ch04_check.py   (fill in, then run)
    python3 genon/out/answer_checks/mathematics_ix_ch04_check.py

The filled worksheet is a C3 artefact and is committed beside the C3 markdown.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
PLANS = ROOT / "data/cloud/content/saved_plans"
OUT = ROOT / "genon/out/answer_checks"

HEADER = '''#!/usr/bin/env python3
"""C3 answer-check worksheet — {subject} · {grade} · chapter {chapter}

GENERATED by genon/extract_determinate.py — then FILLED IN BY HAND, which is the point.

For each item below, read the QUESTION and write the check yourself:
  * `claimed` = what the file ships (already filled in for you, as a sympy expression).
  * `target`  = what the question actually asks for, re-derived FROM THE STEM.

Transcribe from the stem. Do NOT read `method_one_line` first — at S4 the wrong answer shipped
beside a method line that had already found the right one, so a checker who copies the method
confirms the file against itself and sees nothing.

Where an answer is not symbolically expressible (a sentence, a units-bearing quantity, a
multi-part explanation), set `target = None` and record the verdict in the `note` — a judged
item is still a checked item, but say that it was judged.

Run it when filled. Every item must print OK or WRONG. Any WRONG is an S1 defect.
"""
from sympy import symbols, expand, simplify, factor, sympify, Rational, sqrt, Eq, solve

x, y, z, m, n, p, q, r, a, b, c, t, u, v = symbols('x y z m n p q r a b c t u v')

CHECKS = []  # (label, claimed, target, note)

'''

STUB = '''
# ---------------------------------------------------------------------------------------
# item {idx}  ·  {file}  ·  {qtype}  ·  verified={verified}
# Q: {stem}
# SHIPPED: {answer}
# ---------------------------------------------------------------------------------------
CHECKS.append((
    "{label}",
    None,   # claimed  — transcribe the shipped answer above as a sympy expression
    None,   # target   — re-derive from the QUESTION, not from method_one_line
    "",     # note     — required when either side is None (judged, not computed)
))
'''

FOOTER = '''

# ---------------------------------------------------------------------------------------
if __name__ == "__main__":
    wrong = judged = 0
    for label, claimed, target, note in CHECKS:
        if claimed is None or target is None:
            judged += 1
            verdict = "JUDGED"
            if not note:
                verdict = "INCOMPLETE — a None side needs a note"
                wrong += 1
        else:
            ok = simplify(sympify(claimed) - sympify(target)) == 0
            verdict = "OK" if ok else "WRONG"
            wrong += 0 if ok else 1
        print(f"{verdict:12} {label}" + (f"  | {note}" if note else ""))
    print(f"\\n{len(CHECKS)} determinate items · {judged} judged · {wrong} WRONG")
    raise SystemExit(1 if wrong else 0)
'''


def iter_items(obj):
    """Every leaf ITEM in a saved plan, whatever container its stage wraps them in.

    THREE shapes, not two (corrected 2026-08-10, S7 — this walker returned ZERO items for
    maths·middle and the check silently passed on an unexamined library):
      • {..., "questions": [...]}                    maths/science SECONDARY
      • "assessment_items": [ item, ... ]            the flat-list stages
      • "assessment_items": [ {section_code, items: [...]}, ... ]   maths MIDDLE + PREP

    The third is the group-nested container `carriers.item_groups` recognises. A group dict
    is NOT an item — it has no answer and no stem — so yielding it produced no rows and the
    worksheet came back empty, which reads exactly like "this library has no determinate
    answers". Detected by shape, never by subject."""
    if isinstance(obj, dict):
        if isinstance(obj.get("questions"), list):
            yield from obj["questions"]
        ai = obj.get("assessment_items")
        if isinstance(ai, list):
            for entry in ai:
                if isinstance(entry, dict) and isinstance(entry.get("items"), list):
                    yield from entry["items"]          # group-nested (middle / prep)
                else:
                    yield entry                        # already a leaf item
        for value in obj.values():
            yield from iter_items(value)
    elif isinstance(obj, list):
        for value in obj:
            yield from iter_items(value)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a C3 answer-check worksheet.")
    parser.add_argument("subject")
    parser.add_argument("grade")
    parser.add_argument("chapter", type=int)
    args = parser.parse_args()

    if args.subject != "mathematics":
        print(f"NOTE: {args.subject} items are judged, not computed — this check is defined "
              f"for mathematics only (testing.md C3, maths sub-check). Generating anyway.",
              file=sys.stderr)

    folder = PLANS / args.subject / args.grade
    files = sorted(folder.glob(f"ch_{args.chapter:02d}_canonical*.json"))
    if not files:
        print(f"no installed library at {folder}/ch_{args.chapter:02d}_canonical*.json")
        return 1

    body = []
    total = 0
    for path in files:
        doc = json.loads(path.read_text(encoding="utf-8"))
        for idx, item in enumerate(iter_items(doc), 1):
            # TWO FIELD FAMILIES, per the registry spec's maths column. SECONDARY is the
            # hybrid — `question_text` with expected_answer/method_one_line at the TOP level.
            # MIDDLE and PREPARATORY put the stem in `prompt` and both answer fields inside
            # `teacher_guide`. Reading only the secondary shape is why this returned nothing
            # on maths·VII (2026-08-10, S7).
            if not isinstance(item, dict):
                continue
            tg = item.get("teacher_guide") if isinstance(item.get("teacher_guide"), dict) else {}
            answer = str(item.get("expected_answer") or tg.get("expected_answer") or "").strip()
            method = str(item.get("method_one_line") or tg.get("method_one_line") or "").strip()
            if not answer and not method:
                continue
            total += 1
            stem = " ".join(str(item.get("question_text") or item.get("prompt") or "").split())
            body.append(STUB.format(
                idx=idx,
                file=path.name,
                qtype=item.get("question_type"),
                verified=item.get("verified"),
                stem=stem if len(stem) <= 400 else stem[:397] + "...",
                answer=answer or "(no expected_answer — method_one_line only)",
                label=f"{path.stem.replace('ch_%02d_canonical' % args.chapter, '') or 'top'}"
                      f" #{idx}",
            ))

    OUT.mkdir(parents=True, exist_ok=True)
    dest = OUT / f"{args.subject}_{args.grade}_ch{args.chapter:02d}_check.py"
    # A FILLED WORKSHEET IS AN ARTEFACT, NOT A SCRATCH FILE (2026-08-10, S7).
    # Re-running the extractor silently overwrote `mathematics_ix_ch04_check.py` — S4's
    # completed 25-check worksheet, which testing.md C3 cites BY NAME as the regression test
    # for the ARV-D-084 repair. It was recovered from git, but only because someone happened
    # to look. A worksheet is filled by hand over an hour of judgement and the tool that
    # generates the blank must not be able to destroy it in a keystroke.
    if dest.is_file():
        existing = dest.read_text(encoding="utf-8")
        # A BLANK stub has one "None,   # claimed" line per CHECKS.append. Any shortfall means
        # a human has transcribed at least one — i.e. the file is partly or wholly filled.
        # (The first version of this guard counted a string the stub never contains, so it
        # never fired and overwrote the artefact a SECOND time. Assert against the real stub.)
        appends = existing.count("CHECKS.append((")
        blanks = existing.count("None,   # claimed")
        if appends and blanks < appends and "--force" not in sys.argv:
            print(f"REFUSING to overwrite {dest.relative_to(ROOT)} — it is FILLED "
                  f"(a completed C3 artefact). Move it aside, or pass --force if you truly "
                  f"mean to discard the transcriptions.", file=sys.stderr)
            return 1
    dest.write_text(
        HEADER.format(subject=args.subject, grade=args.grade, chapter=args.chapter)
        + "".join(body) + FOOTER,
        encoding="utf-8",
    )
    dest.chmod(0o755)

    print(f"{total} determinate item(s) across {len(files)} file(s) → "
          f"{dest.relative_to(ROOT)}")
    print("Fill in `claimed` and `target` for each, then run it. Any WRONG is an S1 defect.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
